version: "2"
services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    env_file: .env
    restart: always
    volumes:
      - $PWD/config/mysql/data:/var/lib/mysql

  app:
    image: docker/${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-app
    build: ./wordpress
    env_file: .env
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
    hostname: app
    tty: true
    cap_add:
      - ALL
    restart: always
    volumes:
      - $PWD:/var/www/html
      - $PWD/config/apache2/sites:/etc/apache2/sites-enabled
      - $PWD/config/apache2/logs:/var/log/apache2
      - $PWD/config/apache2/conf/apache2.conf:/etc/apache2/apache2.conf
      - $PWD/config/php/php.ini:/usr/local/etc/php/php.ini
